[template]
cargo_generate_version = ">=0.10.0"

[placeholders]
fast_compiles = { type = "bool", prompt = "Enable fast compiles for debug? (note: debug in vscode does not work!)" }
bevy_version = { type = "string", prompt = "Bevy version?", choices = [
    "0.6",
    "git",
] }

[hooks]
post = ["final-msg.rhai"]

[conditional.'fast_compiles == false']
ignore = [ "rust-toolchain.toml", ".cargo" ]
