[template]
cargo_generate_version = ">=0.10.0"
ignore = [
    "README.md",
    ".vscode/settings.json",
    "assets/template-expansion.gif",
    ".github",
    "target",
]

[placeholders]
github_username = { type = "string", prompt = "GitHub username:" }
fast_compiles = { type = "bool", prompt = "Enable fast compiles for debug?" }
bevy_version = { type = "string", prompt = "Bevy version?", choices = [
    "latest (0.5)",
    "git",
] }

[hooks]
post = ["rename.rhai"]

[conditional.'crate_type == "lib"']
ignore = ["src/main.rs"]

[conditional.'fast_compiles == false']
ignore = ["rust-toolchain.toml", ".cargo"]
