[template]
cargo_generate_version = ">=0.16.0"

[hooks]
post = ["final-msg.rhai"]

[placeholders]
gh_username = { type = "string", prompt = "Github Username?", regex="\\w+" }

[conditional.'within_cargo_project == false'.placeholders]
ide = { type = "string", prompt = "Which IDE to use?", default = "vscode", choices = ["none", "vscode"] }

# expansion as a library crate
[conditional.'crate_type == "lib"']
ignore = ["src/main.rs", "assets"]

# expansion as a binary
[conditional.'crate_type != "lib"']
ignore = ["src/lib.rs", "tests"]

# when binary, ark for these placeholders
[conditional.'crate_type != "lib"'.placeholders]
camera = { type = "string", prompt = "Camera type?", choices = [
    "2D",
    "3D",
    "None",
], default = "2D" }

[conditional.'within_cargo_project']
ignore = [
    ".github",
    ".vscode",
    ".gitignore",
]

[conditional.'within_cargo_project && is_init']
ignore = ["README.md", "Cargo.toml"]

[conditional.'within_cargo_project == false && ide != "vscode"']
ignore = [".vscode"]
