[package]
name = "{{project-name}}"
version = "0.1.0"
edition = "2021"
resolver = "2"

[dependencies]
bevy = { version = "0.7", default-features = false }
bevy-embasset = "0.5"

paste = "1.0"
strum = { version = "0.24", features = ["derive"] }
